language: node_js

sudo: false

node_js:
  - '12'

cache:
  apt: true
  yarn: true
  directories:
    - node_modules

install:
  - npm i yarn -g
  - yarn global add vuepress

script:
  - yarn docs:build

after_script:
  - git config --global user.name ${user_name}
  - git config --global user.email ${user_email}
  - git add .
  - git commit -m ":construction_worker:- Build & Deploy by Travis CI"
  - git push --force --quiet https://${travis_token}@${git_address} master
  