language: node_js

env:
  global:
    - GH_REF: github.com/syun0216/Front-end-notes.git

sudo: false

node_js:
  - '12'

cache:
  apt: true
  yarn: true
  directories:
    - node_modules

install:
  - npm i yarn -g
  - yarn global add vuepress

script:
  - yarn docs:build

after_success:
  - git config --global user.name syun0216
  - git config --global user.email 517897442@qq.com
  - git init
  - git add .
  - git commit -m ":construction_worker:- Build & Deploy by Travis CI"
  # 这里的 REPO_TOKEN 即之前在 travis 项目的环境变量里添加的
  - git push --force --quiet "https://${REPO_TOKEN}@${GH_REF}" master